name: hello world
on:
   push:
    branches:
      - main
jobs:
  first-hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: print message
        run: echo "hello world ga tests"
   run-pytest:
     runs-on: ubuntu-latest
     steps:
       - name: checkout code
         uses: actions/checkout@v3
       - name: setup python
         uses: actions/checkout@v3
         with:
           python-version: 3.9
      - name: install depenndencies
        run:
          python -m pip install --upgrade pip
          pip install pytest
      - name: run testcases
        run: pytest
         
